// auth
export const STORAGE_KEY_TOKEN = 'STORAGE_KEY_TOKEN';
export const STORAGE_KEY_USERNAME = 'STORAGE_KEY_USERNAME';

// utils
export const MOMENTJS_DATE_FORMAT_EN = 'YYYY-MM-DD'
export const MOMENTJS_DATE_FORMAT_IT = 'DD/MM/YYYY'
